# Generated by Django 5.2.4 on 2025-07-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='Office-Tidy-Up', max_length=200, unique=True),
        ),
    ]
